filetype off
set rtp+=vader.vim
set rtp+=.
filetype plugin indent on
syntax enable

fun GetLastMessage()
  redir => msgs
  silent messages
  redir END
  return get(split(msgs, "\n"), -1, "")
endf

let g:vigun_dry_run=1
