#!/usr/bin/env bash

set -e

if [ -z "$CI" ]; then
  cmd=nvim
else
  if [ -x ./nvim-linux-x86_64/bin/nvim ]; then
    cmd=./nvim-linux-x86_64/bin/nvim
  else
    cmd=nvim
  fi
fi

if [ -n "$1" ]; then
  path=$1
else
  path=lua/vigun/tests/
fi
$cmd -es -u ./test/vimrc -c "PlenaryBustedDirectory $path { sequential = true }"
