#!/usr/bin/env bash

set -e

test_file=${1:-test/**/*.vader}

if [ -z "$CI" ]; then
  cmd=nvim
else
  cmd=./squashfs-root/usr/bin/nvim
fi

$cmd -es -u ./test/vimrc -c "Vader! $test_file"

echo "\n== Lua config tests (plenary) =="

$cmd -es -u ./test/vimrc -c "PlenaryBustedDirectory lua/vigun/tests/ { sequential = true }"
