version: 2.1
orbs:
  node: circleci/node@5.0.3
jobs:
  run_tests:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install --yes git vim
      - run: sudo curl -LO https://github.com/neovim/neovim/releases/download/stable/nvim.appimage
      - run: sudo chmod +x nvim.appimage
      - run: sudo ./nvim.appimage --appimage-extract
      - run: sudo chmod -R a+rwx ./squashfs-root
      - run: ./run_tests
workflows:
   test:
     jobs:
       - run_tests
