name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update apt cache
        run: sudo apt-get update -y

      - name: Download Neovim stable AppImage
        run: |
          curl -L -o nvim.appimage https://github.com/neovim/neovim/releases/download/stable/nvim-linux-arm64.appimage
          chmod +x nvim.appimage

      - name: Extract AppImage
        run: ./nvim.appimage --appimage-extract

      - name: Make extracted AppImage executable
        run: chmod -R a+rwx ./squashfs-root

      - name: Run tests
        run: ./run_tests
